# Form implementation generated from reading ui file 'camera.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1176, 842)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, -40, 1441, 900))
        self.frame.setStyleSheet("#frame {\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1,\n"
"                                      stop:0 #0f172a, stop:1 #1e293b);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.frHeader = QtWidgets.QFrame(parent=self.frame)
        self.frHeader.setGeometry(QtCore.QRect(0, 40, 1131, 91))
        self.frHeader.setStyleSheet("#frHeader {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1,\n"
"                                      stop:0 #0f172a, stop:1 #1e293b);\n"
" padding : 8px\n"
"}\n"
"\n"
"#lblTitle {\n"
"    color: white;\n"
"    font-size: 24px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"#btnCamera{\n"
"    color: white;\n"
"    font-size: 14px;\n"
"    background-color: #27ae60;\n"
"    border-radius: 5px;\n"
"   font-weight: bold;\n"
"    padding: 10px;\n"
"    margin-left: 50%;\n"
"}\n"
"")
        self.frHeader.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frHeader.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frHeader.setObjectName("frHeader")
        self.layoutWidget = QtWidgets.QWidget(parent=self.frHeader)
        self.layoutWidget.setGeometry(QtCore.QRect(347, 10, 231, 81))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lblTitle = QtWidgets.QLabel(parent=self.layoutWidget)
        self.lblTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblTitle.setObjectName("lblTitle")
        self.verticalLayout_3.addWidget(self.lblTitle)
        self.frEntryCheck = QtWidgets.QFrame(parent=self.frame)
        self.frEntryCheck.setGeometry(QtCore.QRect(790, 140, 341, 591))
        self.frEntryCheck.setStyleSheet("/* --- Frame / GroupBox Entry Check --- */\n"
"QFrame#frEntryCheck {\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1,\n"
"                                      stop:0 #0f172a, stop:1 #1e293b);\n"
"    border: 1px solid #374151; /* slate-700 */\n"
"        border-radius: 8px; \n"
"}\n"
"\n"
"/* --- Title QLabel --- */\n"
"QLabel#lblKiemTra {\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    color: white;\n"
"    qproperty-alignment: \'AlignHCenter\';\n"
"}\n"
"\n"
"\n"
"/* --- Form Labels --- */\n"
"QLabel#lblName, QLabel#lblPlate, #lblCount, #lblRecently, #lblTime{\n"
"    color: #d1d5db; /* slate-300 */\n"
"    font-weight: bold;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"/* --- QLineEdit --- */\n"
"QLineEdit#lineEditName, QLineEdit#lineEditPlate, #lineEditCount, #lineEditRecently, #time, #lineEditCheck, #lineEditPlate_2{\n"
"    background-color: #374151; /* slate-700 */\n"
"    color: white;\n"
"    padding: 6px 10px;\n"
"    border: 1px solid #4b5563; /* slate-600 */\n"
"    border-radius: 6px;\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLineEdit#lineEditName:focus, QLineEdit#lineEditPlate:focus {\n"
"    border: 1px solid #3b82f6; /* blue-500 */\n"
"    outline: none;\n"
"}\n"
"\n"
"/* --- QPushButton cơ bản --- */\n"
"QPushButton#btnVao,\n"
"QPushButton#btnRa \n"
"{\n"
"    background-color: red; /* emerald-600 */\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    padding: 10px;\n"
"    border-radius: 8px;\n"
"margin : 10px;\n"
"}\n"
"\n"
"QPushButton#btnKiemTra {\n"
"    background-color: green; /* emerald-600 */\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    padding: 10px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"/* --- Hover --- */\n"
"QPushButton#btnVao:hover,\n"
"QPushButton#btnRa:hover {\n"
"    background-color: #059669; /* emerald-700 */\n"
"}\n"
"\n"
"QLabel#lblKiemTra{\n"
"     color: #d1d5db; /* slate-300 */\n"
"    font-weight: bold;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"/* --- Disabled --- */\n"
"QPushButton#btnVao:disabled,\n"
"QPushButton#btnRa:disabled {\n"
"    background-color: #6b7280; /* slate-600 */\n"
"    color: #d1d5db; /* slate-300 */\n"
"    border: none;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"#lblKetQua{\n"
"    font-size: 20px;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"}")
        self.frEntryCheck.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frEntryCheck.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frEntryCheck.setObjectName("frEntryCheck")
        self.formLayoutWidget = QtWidgets.QWidget(parent=self.frEntryCheck)
        self.formLayoutWidget.setGeometry(QtCore.QRect(30, 120, 281, 182))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setVerticalSpacing(10)
        self.formLayout.setObjectName("formLayout")
        self.lblPlate = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.lblPlate.setObjectName("lblPlate")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblPlate)
        self.lineEditPlate = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.lineEditPlate.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEditPlate.setObjectName("lineEditPlate")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEditPlate)
        self.lblRecently = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.lblRecently.setObjectName("lblRecently")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblRecently)
        self.lineEditRecently = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.lineEditRecently.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEditRecently.setObjectName("lineEditRecently")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEditRecently)
        self.lblCount = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.lblCount.setObjectName("lblCount")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblCount)
        self.lineEditCount = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.lineEditCount.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEditCount.setObjectName("lineEditCount")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEditCount)
        self.lblName = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.lblName.setObjectName("lblName")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblName)
        self.lineEditName = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.lineEditName.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEditName.setObjectName("lineEditName")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEditName)
        self.time = QtWidgets.QLineEdit(parent=self.frEntryCheck)
        self.time.setGeometry(QtCore.QRect(30, 80, 281, 31))
        self.time.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.time.setObjectName("time")
        self.lblTime = QtWidgets.QLabel(parent=self.frEntryCheck)
        self.lblTime.setGeometry(QtCore.QRect(30, 40, 71, 31))
        self.lblTime.setObjectName("lblTime")
        self.lblKetQua = QtWidgets.QLabel(parent=self.frEntryCheck)
        self.lblKetQua.setGeometry(QtCore.QRect(130, 10, 91, 31))
        self.lblKetQua.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblKetQua.setObjectName("lblKetQua")
        self.layoutWidget1 = QtWidgets.QWidget(parent=self.frEntryCheck)
        self.layoutWidget1.setGeometry(QtCore.QRect(30, 480, 271, 58))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btnVao = QtWidgets.QPushButton(parent=self.layoutWidget1)
        self.btnVao.setObjectName("btnVao")
        self.horizontalLayout_4.addWidget(self.btnVao)
        self.btnRa = QtWidgets.QPushButton(parent=self.layoutWidget1)
        self.btnRa.setObjectName("btnRa")
        self.horizontalLayout_4.addWidget(self.btnRa)
        self.lineEditCheck = QtWidgets.QLineEdit(parent=self.frEntryCheck)
        self.lineEditCheck.setGeometry(QtCore.QRect(30, 400, 281, 51))
        self.lineEditCheck.setObjectName("lineEditCheck")
        self.btnKiemTra = QtWidgets.QPushButton(parent=self.frEntryCheck)
        self.btnKiemTra.setGeometry(QtCore.QRect(220, 330, 93, 51))
        self.btnKiemTra.setObjectName("btnKiemTra")
        self.lineEditPlate_2 = QtWidgets.QLineEdit(parent=self.frEntryCheck)
        self.lineEditPlate_2.setGeometry(QtCore.QRect(30, 330, 181, 51))
        self.lineEditPlate_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEditPlate_2.setObjectName("lineEditPlate_2")
        self.frame_2 = QtWidgets.QFrame(parent=self.frame)
        self.frame_2.setGeometry(QtCore.QRect(20, 140, 761, 591))
        self.frame_2.setStyleSheet("#frame_2 {\n"
"    border: 1px solid #374151; /* slate-700 */\n"
"    border-radius: 10px;             /* bo góc 8px */\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1,\n"
"                                      stop:0 #0f172a, stop:1 #1e293b);\n"
"}\n"
"QPushButton#btnScan, #btnConfirm {\n"
"    background-color: #1B9CFC;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    padding: 10px;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"/* --- Hover --- */\n"
"QPushButton#btnScan:hover {\n"
"    background-color: #059669;\n"
"}\n"
"\n"
"/* --- Disabled --- */\n"
"QPushButton#btnScan:disabled {\n"
"    background-color: #6b7280;\n"
"    color: #d1d5db;\n"
"    border: none;\n"
"}\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frCamera = QtWidgets.QFrame(parent=self.frame_2)
        self.frCamera.setGeometry(QtCore.QRect(10, 20, 741, 501))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frCamera.sizePolicy().hasHeightForWidth())
        self.frCamera.setSizePolicy(sizePolicy)
        self.frCamera.setStyleSheet("")
        self.frCamera.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frCamera.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frCamera.setObjectName("frCamera")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frCamera)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.FrameFace = QtWidgets.QFrame(parent=self.frCamera)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FrameFace.sizePolicy().hasHeightForWidth())
        self.FrameFace.setSizePolicy(sizePolicy)
        self.FrameFace.setStyleSheet("QFrame#FrameFace {\n"
"\n"
"     border-radius: 8px; \n"
"}\n"
"#lblFaceImage {\n"
"    margin: 25px;\n"
"    display: flex;\n"
"    justify-content: center;   /* Căn giữa ngang */\n"
"    align-items: center;    \n"
"    border: 1px solid #374151; /* slate-700 */\n"
"}\n"
"\n"
"\n"
"#lblCamera {\n"
"     border: 1px solid #374151; /* slate-700 */\n"
"   \n"
"}\n"
"\n"
"#lbltitle {\n"
"    color: white;\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    margin-left: 8px;\n"
"}\n"
"#lblNameResult {\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    border: 1px solid #374151; /* slate-700 */\n"
"    padding: 5px;\n"
"}\n"
"")
        self.FrameFace.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.FrameFace.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.FrameFace.setObjectName("FrameFace")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.FrameFace)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbltitle = QtWidgets.QLabel(parent=self.FrameFace)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbltitle.sizePolicy().hasHeightForWidth())
        self.lbltitle.setSizePolicy(sizePolicy)
        self.lbltitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.lbltitle.setObjectName("lbltitle")
        self.verticalLayout.addWidget(self.lbltitle)
        self.lblCamera = QtWidgets.QLabel(parent=self.FrameFace)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCamera.sizePolicy().hasHeightForWidth())
        self.lblCamera.setSizePolicy(sizePolicy)
        self.lblCamera.setMinimumSize(QtCore.QSize(350, 200))
        self.lblCamera.setMaximumSize(QtCore.QSize(350, 200))
        self.lblCamera.setStyleSheet("")
        self.lblCamera.setText("")
        self.lblCamera.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblCamera.setObjectName("lblCamera")
        self.verticalLayout.addWidget(self.lblCamera)
        self.lblFaceImage = QtWidgets.QLabel(parent=self.FrameFace)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblFaceImage.sizePolicy().hasHeightForWidth())
        self.lblFaceImage.setSizePolicy(sizePolicy)
        self.lblFaceImage.setStyleSheet("")
        self.lblFaceImage.setText("")
        self.lblFaceImage.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblFaceImage.setObjectName("lblFaceImage")
        self.verticalLayout.addWidget(self.lblFaceImage)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout.addWidget(self.FrameFace)
        self.FramePlate = QtWidgets.QFrame(parent=self.frCamera)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FramePlate.sizePolicy().hasHeightForWidth())
        self.FramePlate.setSizePolicy(sizePolicy)
        self.FramePlate.setStyleSheet("QFrame#FramePlate {\n"
"\n"
"\n"
"}\n"
"\n"
"#lblCamera_2 {\n"
"    \n"
"     border: 1px solid #374151; /* slate-700 */\n"
"}\n"
"\n"
"#lbltitle_2 {\n"
"    color: white;\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    margin-left: 8px;\n"
"}\n"
"#lblPlateResult{\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    border: 1px solid #374151; /* slate-700 */\n"
"    padding: 5px;\n"
"}\n"
"#lblPlateImage{\n"
"    margin: 25px;\n"
"display: flex;\n"
"    justify-content: center;   /* Căn giữa ngang */\n"
"    align-items: center;    \n"
"        border: 1px solid #374151; /* slate-700 */\n"
"}\n"
"\n"
"QPushButton#btnScanPlate {\n"
"    background-color: #1B9CFC;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    padding: 10px;\n"
"    border-radius: 8px;\n"
"\n"
"}\n"
"\n"
"/* --- Hover --- */\n"
"QPushButton#btnScanPlate:hover\n"
" {\n"
"    background-color: #059669; /* emerald-700 */\n"
"}\n"
"\n"
"/* --- Disabled --- */\n"
"QPushButton#btnScanPlate:disabled {\n"
"    background-color: #6b7280; /* slate-600 */\n"
"    color: #d1d5db; /* slate-300 */\n"
"    border: none;\n"
"}")
        self.FramePlate.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.FramePlate.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.FramePlate.setObjectName("FramePlate")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.FramePlate)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lbltitle_2 = QtWidgets.QLabel(parent=self.FramePlate)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbltitle_2.sizePolicy().hasHeightForWidth())
        self.lbltitle_2.setSizePolicy(sizePolicy)
        self.lbltitle_2.setObjectName("lbltitle_2")
        self.verticalLayout_2.addWidget(self.lbltitle_2)
        self.lblCamera_2 = QtWidgets.QLabel(parent=self.FramePlate)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCamera_2.sizePolicy().hasHeightForWidth())
        self.lblCamera_2.setSizePolicy(sizePolicy)
        self.lblCamera_2.setMinimumSize(QtCore.QSize(350, 200))
        self.lblCamera_2.setMaximumSize(QtCore.QSize(350, 200))
        self.lblCamera_2.setStyleSheet("")
        self.lblCamera_2.setText("")
        self.lblCamera_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblCamera_2.setObjectName("lblCamera_2")
        self.verticalLayout_2.addWidget(self.lblCamera_2)
        self.lblPlateImage = QtWidgets.QLabel(parent=self.FramePlate)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblPlateImage.sizePolicy().hasHeightForWidth())
        self.lblPlateImage.setSizePolicy(sizePolicy)
        self.lblPlateImage.setMinimumSize(QtCore.QSize(250, 150))
        self.lblPlateImage.setStyleSheet("")
        self.lblPlateImage.setText("")
        self.lblPlateImage.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblPlateImage.setObjectName("lblPlateImage")
        self.verticalLayout_2.addWidget(self.lblPlateImage)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout.addWidget(self.FramePlate)
        self.btnScan = QtWidgets.QPushButton(parent=self.frame_2)
        self.btnScan.setGeometry(QtCore.QRect(270, 540, 81, 41))
        self.btnScan.setStyleSheet("btnScan {\n"
"    background-color: #1B9CFC;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    padding: 10px;\n"
"    border-radius: 8px;\n"
"\n"
"}\n"
"\n"
"/* --- Hover --- */\n"
"btnScan:hover\n"
"{\n"
"    background-color: #059669; /* emerald-700 */\n"
"}\n"
"\n"
"/* --- Disabled --- */\n"
"btnScan:disabled\n"
"{\n"
"    background-color: #6b7280; /* slate-600 */\n"
"    color: #d1d5db; /* slate-300 */\n"
"    border: none;\n"
"}")
        self.btnScan.setObjectName("btnScan")
        self.btnConfirm = QtWidgets.QPushButton(parent=self.frame_2)
        self.btnConfirm.setGeometry(QtCore.QRect(390, 540, 91, 41))
        self.btnConfirm.setStyleSheet("btnScan {\n"
"    background-color: #1B9CFC;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    padding: 10px;\n"
"    border-radius: 8px;\n"
"\n"
"}\n"
"\n"
"/* --- Hover --- */\n"
"btnScan:hover\n"
"{\n"
"    background-color: #059669; /* emerald-700 */\n"
"}\n"
"\n"
"/* --- Disabled --- */\n"
"btnScan:disabled\n"
"{\n"
"    background-color: #6b7280; /* slate-600 */\n"
"    color: #d1d5db; /* slate-300 */\n"
"    border: none;\n"
"}")
        self.btnConfirm.setObjectName("btnConfirm")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1176, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lblTitle.setText(_translate("MainWindow", "QUẢN LÝ RA VÀO "))
        self.lblPlate.setText(_translate("MainWindow", "BIỂN SỐ"))
        self.lblRecently.setText(_translate("MainWindow", "GẦN ĐÂY"))
        self.lblCount.setText(_translate("MainWindow", "SỐ LẦN ĐẬU"))
        self.lblName.setText(_translate("MainWindow", "TÊN"))
        self.lblTime.setText(_translate("MainWindow", "THỜI GIAN"))
        self.lblKetQua.setText(_translate("MainWindow", "KẾT QUẢ"))
        self.btnVao.setText(_translate("MainWindow", "VÀO"))
        self.btnRa.setText(_translate("MainWindow", "RA"))
        self.btnKiemTra.setText(_translate("MainWindow", "KIỂM TRA"))
        self.lbltitle.setText(_translate("MainWindow", "KHUÔN MẶT"))
        self.lbltitle_2.setText(_translate("MainWindow", "BIỂN SỐ"))
        self.btnScan.setText(_translate("MainWindow", "CHỤP"))
        self.btnConfirm.setText(_translate("MainWindow", "XÁC NHẬN"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
