# Form implementation generated from reading ui file 'camera.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1798, 842)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, -40, 1751, 900))
        self.frame.setStyleSheet("#frame {\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1,\n"
"                                      stop:0 #0f172a, stop:1 #1e293b);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.frHeader = QtWidgets.QFrame(parent=self.frame)
        self.frHeader.setGeometry(QtCore.QRect(0, 40, 1051, 91))
        self.frHeader.setStyleSheet("#frHeader {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1,\n"
"                                      stop:0 #0f172a, stop:1 #1e293b);\n"
" padding : 8px\n"
"}\n"
"\n"
"#lblTitle {\n"
"    color: white;\n"
"    font-size: 24px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"#btnCamera{\n"
"    color: white;\n"
"    font-size: 14px;\n"
"    background-color: #27ae60;\n"
"    border-radius: 5px;\n"
"   font-weight: bold;\n"
"    padding: 10px;\n"
"    margin-left: 50%;\n"
"}\n"
"")
        self.frHeader.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frHeader.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frHeader.setObjectName("frHeader")
        self.layoutWidget = QtWidgets.QWidget(parent=self.frHeader)
        self.layoutWidget.setGeometry(QtCore.QRect(347, 10, 231, 81))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lblTitle = QtWidgets.QLabel(parent=self.layoutWidget)
        self.lblTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblTitle.setObjectName("lblTitle")
        self.verticalLayout_3.addWidget(self.lblTitle)
        self.frEntryCheck = QtWidgets.QFrame(parent=self.frame)
        self.frEntryCheck.setGeometry(QtCore.QRect(730, 140, 311, 651))
        self.frEntryCheck.setStyleSheet("/* --- Frame / GroupBox Entry Check --- */\n"
"QFrame#frEntryCheck {\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1,\n"
"                                      stop:0 #0f172a, stop:1 #1e293b);\n"
"    border: 1px solid #374151; /* slate-700 */\n"
"        border-radius: 8px; \n"
"}\n"
"\n"
"/* --- Title QLabel --- */\n"
"QLabel#lblKiemTra {\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    color: white;\n"
"    qproperty-alignment: \'AlignHCenter\';\n"
"}\n"
"\n"
"\n"
"/* --- Form Labels --- */\n"
"QLabel#lblName, QLabel#lblPlate, #lblCount, #lblRecently, #lblTime{\n"
"    color: #d1d5db; /* slate-300 */\n"
"    font-weight: bold;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"/* --- QLineEdit --- */\n"
"QLineEdit#lineEditName, QLineEdit#lineEditPlate, #lineEditCount, #lineEditRecently, #time, #lineEditCheck, #lineEditPlate_2{\n"
"    background-color: #374151; /* slate-700 */\n"
"    color: white;\n"
"    padding: 6px 10px;\n"
"    border: 1px solid #4b5563; /* slate-600 */\n"
"    border-radius: 6px;\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLineEdit#lineEditName:focus, QLineEdit#lineEditPlate:focus {\n"
"    border: 1px solid #3b82f6; /* blue-500 */\n"
"    outline: none;\n"
"}\n"
"\n"
"/* --- QPushButton cơ bản --- */\n"
"QPushButton#btnVao,\n"
"QPushButton#btnRa \n"
"{\n"
"    background-color: red; /* emerald-600 */\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    padding: 10px;\n"
"    border-radius: 8px;\n"
"margin : 10px;\n"
"}\n"
"\n"
"QPushButton#btnKiemTra {\n"
"    background-color: green; /* emerald-600 */\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    padding: 10px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"/* --- Hover --- */\n"
"QPushButton#btnVao:hover,\n"
"QPushButton#btnRa:hover {\n"
"    background-color: #059669; /* emerald-700 */\n"
"}\n"
"\n"
"QLabel#lblKiemTra{\n"
"     color: #d1d5db; /* slate-300 */\n"
"    font-weight: bold;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"/* --- Disabled --- */\n"
"QPushButton#btnVao:disabled,\n"
"QPushButton#btnRa:disabled {\n"
"    background-color: #6b7280; /* slate-600 */\n"
"    color: #d1d5db; /* slate-300 */\n"
"    border: none;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"#lblKetQua{\n"
"    font-size: 20px;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"}")
        self.frEntryCheck.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frEntryCheck.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frEntryCheck.setObjectName("frEntryCheck")
        self.formLayoutWidget = QtWidgets.QWidget(parent=self.frEntryCheck)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 170, 281, 181))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setVerticalSpacing(10)
        self.formLayout.setObjectName("formLayout")
        self.lineEditName = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.lineEditName.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEditName.setObjectName("lineEditName")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEditName)
        self.lblPlate = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.lblPlate.setObjectName("lblPlate")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblPlate)
        self.lineEditPlate = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.lineEditPlate.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEditPlate.setObjectName("lineEditPlate")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEditPlate)
        self.lblRecently = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.lblRecently.setObjectName("lblRecently")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblRecently)
        self.lineEditRecently = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.lineEditRecently.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEditRecently.setObjectName("lineEditRecently")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEditRecently)
        self.lblCount = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.lblCount.setObjectName("lblCount")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblCount)
        self.lineEditCount = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.lineEditCount.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEditCount.setObjectName("lineEditCount")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEditCount)
        self.lblName = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.lblName.setObjectName("lblName")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblName)
        self.time = QtWidgets.QLineEdit(parent=self.frEntryCheck)
        self.time.setGeometry(QtCore.QRect(10, 80, 281, 41))
        self.time.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.time.setObjectName("time")
        self.lblTime = QtWidgets.QLabel(parent=self.frEntryCheck)
        self.lblTime.setGeometry(QtCore.QRect(10, 40, 71, 31))
        self.lblTime.setObjectName("lblTime")
        self.lblKetQua = QtWidgets.QLabel(parent=self.frEntryCheck)
        self.lblKetQua.setGeometry(QtCore.QRect(130, 10, 91, 31))
        self.lblKetQua.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblKetQua.setObjectName("lblKetQua")
        self.layoutWidget1 = QtWidgets.QWidget(parent=self.frEntryCheck)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 560, 281, 58))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btnVao = QtWidgets.QPushButton(parent=self.layoutWidget1)
        self.btnVao.setObjectName("btnVao")
        self.horizontalLayout_4.addWidget(self.btnVao)
        self.btnRa = QtWidgets.QPushButton(parent=self.layoutWidget1)
        self.btnRa.setObjectName("btnRa")
        self.horizontalLayout_4.addWidget(self.btnRa)
        self.lineEditCheck = QtWidgets.QLineEdit(parent=self.frEntryCheck)
        self.lineEditCheck.setGeometry(QtCore.QRect(10, 480, 281, 51))
        self.lineEditCheck.setObjectName("lineEditCheck")
        self.btnKiemTra = QtWidgets.QPushButton(parent=self.frEntryCheck)
        self.btnKiemTra.setGeometry(QtCore.QRect(200, 380, 93, 51))
        self.btnKiemTra.setObjectName("btnKiemTra")
        self.lineEditPlate_2 = QtWidgets.QLineEdit(parent=self.frEntryCheck)
        self.lineEditPlate_2.setGeometry(QtCore.QRect(10, 380, 181, 51))
        self.lineEditPlate_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEditPlate_2.setObjectName("lineEditPlate_2")
        self.frame_2 = QtWidgets.QFrame(parent=self.frame)
        self.frame_2.setGeometry(QtCore.QRect(0, 140, 721, 651))
        self.frame_2.setStyleSheet("#frame_2 {\n"
"    border: 1px solid #374151; /* slate-700 */\n"
"    border-radius: 10px;             /* bo góc 8px */\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1,\n"
"                                      stop:0 #0f172a, stop:1 #1e293b);\n"
"}\n"
"QPushButton#btnScan, #btnConfirm {\n"
"    background-color: #1B9CFC;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    padding: 10px;\n"
"    border-radius: 8px;\n"
"}\n"
"QPushButton#btnConfirm {\n"
"    background-color: red;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    padding: 10px;\n"
"    border-radius: 8px;\n"
"}\n"
"/* --- Hover --- */\n"
"QPushButton#btnScan:hover {\n"
"    background-color: #059669;\n"
"}\n"
"\n"
"/* --- Disabled --- */\n"
"QPushButton#btnScan:disabled {\n"
"    background-color: #6b7280;\n"
"    color: #d1d5db;\n"
"    border: none;\n"
"}\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frCamera = QtWidgets.QFrame(parent=self.frame_2)
        self.frCamera.setGeometry(QtCore.QRect(0, 60, 711, 491))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frCamera.sizePolicy().hasHeightForWidth())
        self.frCamera.setSizePolicy(sizePolicy)
        self.frCamera.setStyleSheet("")
        self.frCamera.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frCamera.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frCamera.setObjectName("frCamera")
        self.FrameFace = QtWidgets.QFrame(parent=self.frCamera)
        self.FrameFace.setGeometry(QtCore.QRect(0, 10, 351, 531))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FrameFace.sizePolicy().hasHeightForWidth())
        self.FrameFace.setSizePolicy(sizePolicy)
        self.FrameFace.setStyleSheet("QFrame#FrameFace {\n"
"\n"
"}\n"
"#lblFaceImage {\n"
"\n"
"    display: flex;\n"
"    justify-content: center;   /* Căn giữa ngang */\n"
"    align-items: center;    \n"
"    border: 1px solid #374151; /* slate-700 */\n"
"}\n"
"\n"
"\n"
"#lblCamera {\n"
"     border: 1px solid #374151; /* slate-700 */\n"
"   \n"
"}\n"
"\n"
"#lbltitle {\n"
"    color: black;\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    margin-left: 8px;\n"
"}\n"
"#lblNameResult {\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    border: 1px solid #374151; /* slate-700 */\n"
"    padding: 5px;\n"
"}\n"
"")
        self.FrameFace.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.FrameFace.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.FrameFace.setObjectName("FrameFace")
        self.layoutWidget2 = QtWidgets.QWidget(parent=self.FrameFace)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 13, 342, 461))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbltitle = QtWidgets.QLabel(parent=self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbltitle.sizePolicy().hasHeightForWidth())
        self.lbltitle.setSizePolicy(sizePolicy)
        self.lbltitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.lbltitle.setObjectName("lbltitle")
        self.verticalLayout.addWidget(self.lbltitle)
        self.lblCamera = QtWidgets.QLabel(parent=self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCamera.sizePolicy().hasHeightForWidth())
        self.lblCamera.setSizePolicy(sizePolicy)
        self.lblCamera.setMinimumSize(QtCore.QSize(340, 200))
        self.lblCamera.setMaximumSize(QtCore.QSize(340, 200))
        self.lblCamera.setStyleSheet("")
        self.lblCamera.setText("")
        self.lblCamera.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblCamera.setObjectName("lblCamera")
        self.verticalLayout.addWidget(self.lblCamera)
        self.lblFaceImage = QtWidgets.QLabel(parent=self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblFaceImage.sizePolicy().hasHeightForWidth())
        self.lblFaceImage.setSizePolicy(sizePolicy)
        self.lblFaceImage.setStyleSheet("")
        self.lblFaceImage.setText("")
        self.lblFaceImage.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblFaceImage.setObjectName("lblFaceImage")
        self.verticalLayout.addWidget(self.lblFaceImage)
        self.FramePlate = QtWidgets.QFrame(parent=self.frCamera)
        self.FramePlate.setGeometry(QtCore.QRect(359, 12, 351, 471))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FramePlate.sizePolicy().hasHeightForWidth())
        self.FramePlate.setSizePolicy(sizePolicy)
        self.FramePlate.setStyleSheet("QFrame#FramePlate {\n"
"\n"
"\n"
"}\n"
"\n"
"#lblCamera_2 {\n"
"    \n"
"     border: 1px solid #374151; /* slate-700 */\n"
"}\n"
"\n"
"#lbltitle_2 {\n"
"    color: black;\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    margin-left: 8px;\n"
"}\n"
"#lblPlateResult{\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    border: 1px solid #374151; /* slate-700 */\n"
"    padding: 5px;\n"
"}\n"
"#lblPlateImage{\n"
"\n"
"display: flex;\n"
"    justify-content: center;   /* Căn giữa ngang */\n"
"    align-items: center;    \n"
"        border: 1px solid #374151; /* slate-700 */\n"
"}\n"
"\n"
"QPushButton#btnScanPlate {\n"
"    background-color: #1B9CFC;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    padding: 10px;\n"
"    border-radius: 8px;\n"
"\n"
"}\n"
"\n"
"/* --- Hover --- */\n"
"QPushButton#btnScanPlate:hover\n"
" {\n"
"    background-color: #059669; /* emerald-700 */\n"
"}\n"
"\n"
"/* --- Disabled --- */\n"
"QPushButton#btnScanPlate:disabled {\n"
"    background-color: #6b7280; /* slate-600 */\n"
"    color: #d1d5db; /* slate-300 */\n"
"    border: none;\n"
"}")
        self.FramePlate.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.FramePlate.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.FramePlate.setObjectName("FramePlate")
        self.layoutWidget3 = QtWidgets.QWidget(parent=self.FramePlate)
        self.layoutWidget3.setGeometry(QtCore.QRect(0, 11, 342, 461))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lbltitle_2 = QtWidgets.QLabel(parent=self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbltitle_2.sizePolicy().hasHeightForWidth())
        self.lbltitle_2.setSizePolicy(sizePolicy)
        self.lbltitle_2.setObjectName("lbltitle_2")
        self.verticalLayout_2.addWidget(self.lbltitle_2)
        self.lblCamera_2 = QtWidgets.QLabel(parent=self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCamera_2.sizePolicy().hasHeightForWidth())
        self.lblCamera_2.setSizePolicy(sizePolicy)
        self.lblCamera_2.setMinimumSize(QtCore.QSize(340, 200))
        self.lblCamera_2.setMaximumSize(QtCore.QSize(340, 200))
        self.lblCamera_2.setStyleSheet("")
        self.lblCamera_2.setText("")
        self.lblCamera_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblCamera_2.setObjectName("lblCamera_2")
        self.verticalLayout_2.addWidget(self.lblCamera_2)
        self.lblPlateImage = QtWidgets.QLabel(parent=self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblPlateImage.sizePolicy().hasHeightForWidth())
        self.lblPlateImage.setSizePolicy(sizePolicy)
        self.lblPlateImage.setMinimumSize(QtCore.QSize(250, 150))
        self.lblPlateImage.setStyleSheet("")
        self.lblPlateImage.setText("")
        self.lblPlateImage.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblPlateImage.setObjectName("lblPlateImage")
        self.verticalLayout_2.addWidget(self.lblPlateImage)
        self.btnScan = QtWidgets.QPushButton(parent=self.frame_2)
        self.btnScan.setGeometry(QtCore.QRect(270, 600, 81, 41))
        self.btnScan.setStyleSheet("btnScan {\n"
"    background-color: #1B9CFC;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    padding: 10px;\n"
"    border-radius: 8px;\n"
"\n"
"}\n"
"\n"
"/* --- Hover --- */\n"
"btnScan:hover\n"
"{\n"
"    background-color: #059669; /* emerald-700 */\n"
"}\n"
"\n"
"/* --- Disabled --- */\n"
"btnScan:disabled\n"
"{\n"
"    background-color: #6b7280; /* slate-600 */\n"
"    color: #d1d5db; /* slate-300 */\n"
"    border: none;\n"
"}")
        self.btnScan.setObjectName("btnScan")
        self.btnConfirm = QtWidgets.QPushButton(parent=self.frame_2)
        self.btnConfirm.setGeometry(QtCore.QRect(390, 600, 91, 41))
        self.btnConfirm.setStyleSheet("btnScan {\n"
"    background-color: #1B9CFC;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    padding: 10px;\n"
"    border-radius: 8px;\n"
"\n"
"}\n"
"\n"
"/* --- Hover --- */\n"
"btnScan:hover\n"
"{\n"
"    background-color: #059669; /* emerald-700 */\n"
"}\n"
"\n"
"/* --- Disabled --- */\n"
"btnScan:disabled\n"
"{\n"
"    background-color: #6b7280; /* slate-600 */\n"
"    color: #d1d5db; /* slate-300 */\n"
"    border: none;\n"
"}")
        self.btnConfirm.setObjectName("btnConfirm")
        self.DangKy = QtWidgets.QFrame(parent=self.frame)
        self.DangKy.setGeometry(QtCore.QRect(1050, 10, 471, 791))
        self.DangKy.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.DangKy.setStyleSheet("QFrame#DangKy{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1,\n"
"                                      stop:0 #0f172a, stop:1 #1e293b);\n"
"    border: 1px solid #374151; /* slate-700 */\n"
"        border-radius: 8px; \n"
"}\n"
"#lblDangKy , #lblHistory{\n"
"    font-size: 20px;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLineEdit#editEmail, QLineEdit,#editFullName, #editSdt{\n"
"    background-color: #374151; /* slate-700 */\n"
"    color: white;\n"
"    padding: 6px 10px;\n"
"    border: 1px solid #4b5563; /* slate-600 */\n"
"    border-radius: 6px;\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLabel#lblEmail, #lblSdt, #lblFullName{\n"
"    color: #d1d5db; /* slate-300 */\n"
"    font-weight: bold;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"#btnSearch, #btnXemLichSu{\n"
"background-color: #1B9CFC;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    padding: 10px;\n"
"    border-radius: 8px;\n"
"\n"
"}\n"
"#btnThem {\n"
"    background-color: #1B9CFC;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    padding: 10px;\n"
"    border-radius: 8px;\n"
"\n"
"}\n"
"#btnSua{\n"
"    background-color: #f9ca24;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    padding: 10px;\n"
"    border-radius: 8px;\n"
"} \n"
"#btnXoa{\n"
"    background-color: red;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    padding: 10px;\n"
"    border-radius: 8px;\n"
"}\n"
" #btnXacNhanDangKy{\n"
"    background-color: green; /* slate-700 */\n"
"    color: white;\n"
"    padding: 6px 10px;\n"
"    border: 1px solid #4b5563; /* slate-600 */\n"
"    border-radius: 6px;\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.DangKy.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.DangKy.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.DangKy.setObjectName("DangKy")
        self.lblDangKy = QtWidgets.QLabel(parent=self.DangKy)
        self.lblDangKy.setGeometry(QtCore.QRect(78, 20, 311, 31))
        self.lblDangKy.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblDangKy.setObjectName("lblDangKy")
        self.formLayoutWidget_3 = QtWidgets.QWidget(parent=self.DangKy)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(10, 160, 301, 131))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.lblFullName = QtWidgets.QLabel(parent=self.formLayoutWidget_3)
        self.lblFullName.setObjectName("lblFullName")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblFullName)
        self.editFullName = QtWidgets.QLineEdit(parent=self.formLayoutWidget_3)
        self.editFullName.setMinimumSize(QtCore.QSize(240, 35))
        self.editFullName.setMaximumSize(QtCore.QSize(240, 35))
        self.editFullName.setObjectName("editFullName")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.editFullName)
        self.lblEmail = QtWidgets.QLabel(parent=self.formLayoutWidget_3)
        self.lblEmail.setObjectName("lblEmail")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblEmail)
        self.editEmail = QtWidgets.QLineEdit(parent=self.formLayoutWidget_3)
        self.editEmail.setMinimumSize(QtCore.QSize(240, 34))
        self.editEmail.setMaximumSize(QtCore.QSize(240, 35))
        self.editEmail.setObjectName("editEmail")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.editEmail)
        self.lblSdt = QtWidgets.QLabel(parent=self.formLayoutWidget_3)
        self.lblSdt.setObjectName("lblSdt")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblSdt)
        self.editSdt = QtWidgets.QLineEdit(parent=self.formLayoutWidget_3)
        self.editSdt.setMinimumSize(QtCore.QSize(240, 35))
        self.editSdt.setMaximumSize(QtCore.QSize(240, 35))
        self.editSdt.setObjectName("editSdt")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.editSdt)
        self.lblHistory = QtWidgets.QLabel(parent=self.DangKy)
        self.lblHistory.setGeometry(QtCore.QRect(74, 413, 311, 61))
        self.lblHistory.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblHistory.setObjectName("lblHistory")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.DangKy)
        self.tableWidget.setGeometry(QtCore.QRect(20, 479, 431, 271))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(11)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(0, 170, 255))
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.NoBrush)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(0, 170, 255))
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.NoBrush)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(0, 170, 255))
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.NoBrush)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(0, 170, 255))
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.NoBrush)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.btnXacNhanDangKy = QtWidgets.QPushButton(parent=self.DangKy)
        self.btnXacNhanDangKy.setGeometry(QtCore.QRect(200, 354, 100, 41))
        self.btnXacNhanDangKy.setStyleSheet("")
        self.btnXacNhanDangKy.setObjectName("btnXacNhanDangKy")
        self.btnSearch = QtWidgets.QPushButton(parent=self.DangKy)
        self.btnSearch.setGeometry(QtCore.QRect(353, 110, 100, 35))
        self.btnSearch.setMinimumSize(QtCore.QSize(100, 35))
        self.btnSearch.setMaximumSize(QtCore.QSize(100, 35))
        self.btnSearch.setStyleSheet("")
        self.btnSearch.setObjectName("btnSearch")
        self.layoutWidget4 = QtWidgets.QWidget(parent=self.DangKy)
        self.layoutWidget4.setGeometry(QtCore.QRect(352, 158, 102, 124))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.btnThem = QtWidgets.QPushButton(parent=self.layoutWidget4)
        self.btnThem.setMinimumSize(QtCore.QSize(100, 35))
        self.btnThem.setMaximumSize(QtCore.QSize(100, 35))
        self.btnThem.setStyleSheet("")
        self.btnThem.setObjectName("btnThem")
        self.verticalLayout_4.addWidget(self.btnThem)
        self.btnSua = QtWidgets.QPushButton(parent=self.layoutWidget4)
        self.btnSua.setMinimumSize(QtCore.QSize(100, 35))
        self.btnSua.setMaximumSize(QtCore.QSize(100, 35))
        self.btnSua.setStyleSheet("")
        self.btnSua.setObjectName("btnSua")
        self.verticalLayout_4.addWidget(self.btnSua)
        self.btnXoa = QtWidgets.QPushButton(parent=self.layoutWidget4)
        self.btnXoa.setMinimumSize(QtCore.QSize(100, 35))
        self.btnXoa.setMaximumSize(QtCore.QSize(100, 35))
        self.btnXoa.setStyleSheet("")
        self.btnXoa.setObjectName("btnXoa")
        self.verticalLayout_4.addWidget(self.btnXoa)
        self.plateNumber = QtWidgets.QLineEdit(parent=self.DangKy)
        self.plateNumber.setGeometry(QtCore.QRect(62, 110, 240, 35))
        self.plateNumber.setMinimumSize(QtCore.QSize(240, 35))
        self.plateNumber.setMaximumSize(QtCore.QSize(240, 35))
        self.plateNumber.setObjectName("plateNumber")
        self.btnDoi = QtWidgets.QPushButton(parent=self.DangKy)
        self.btnDoi.setGeometry(QtCore.QRect(63, 288, 240, 35))
        self.btnDoi.setStyleSheet("")
        self.btnDoi.setObjectName("btnDoi")
        self.checkBox = QtWidgets.QCheckBox(parent=self.DangKy)
        self.checkBox.setGeometry(QtCore.QRect(13, 289, 35, 35))
        self.checkBox.setMinimumSize(QtCore.QSize(35, 35))
        self.checkBox.setMaximumSize(QtCore.QSize(35, 35))
        self.checkBox.setText("")
        self.checkBox.setObjectName("checkBox")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1798, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lblTitle.setText(_translate("MainWindow", "QUẢN LÝ RA VÀO "))
        self.lblPlate.setText(_translate("MainWindow", "BIỂN SỐ"))
        self.lblRecently.setText(_translate("MainWindow", "GẦN ĐÂY"))
        self.lblCount.setText(_translate("MainWindow", "SỐ LẦN ĐẬU"))
        self.lblName.setText(_translate("MainWindow", "TÊN"))
        self.lblTime.setText(_translate("MainWindow", "THỜI GIAN"))
        self.lblKetQua.setText(_translate("MainWindow", "KẾT QUẢ"))
        self.btnVao.setText(_translate("MainWindow", "VÀO"))
        self.btnRa.setText(_translate("MainWindow", "RA"))
        self.btnKiemTra.setText(_translate("MainWindow", "KIỂM TRA"))
        self.lbltitle.setText(_translate("MainWindow", "KHUÔN MẶT"))
        self.lbltitle_2.setText(_translate("MainWindow", "BIỂN SỐ"))
        self.btnScan.setText(_translate("MainWindow", "CHỤP"))
        self.btnConfirm.setText(_translate("MainWindow", "XÁC NHẬN"))
        self.lblDangKy.setText(_translate("MainWindow", "QUẢN LÝ NGƯỜI DÙNG"))
        self.lblFullName.setText(_translate("MainWindow", "HỌ TÊN"))
        self.lblEmail.setText(_translate("MainWindow", "EMAIL"))
        self.lblSdt.setText(_translate("MainWindow", "SĐT"))
        self.lblHistory.setText(_translate("MainWindow", "LỊCH SỬ VÀO RA"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "6"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "7"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "8"))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "9"))
        item = self.tableWidget.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "10"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "BIỂN SỐ "))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "THỜI GIAN VÀO"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "SỐ LƯỢT ĐẬU"))
        self.btnXacNhanDangKy.setText(_translate("MainWindow", "XÁC NHẬN"))
        self.btnSearch.setText(_translate("MainWindow", "TÌM KIẾM"))
        self.btnThem.setText(_translate("MainWindow", "THÊM"))
        self.btnSua.setText(_translate("MainWindow", "SỬA"))
        self.btnXoa.setText(_translate("MainWindow", "XÓA"))
        self.btnDoi.setText(_translate("MainWindow", "THAY ĐỔI NGƯỜI ĐĂNG KÝ"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
